import React, { ReactChildren, ReactChild } from "react";
import { LayoutStyled, HeaderStyled, FooterStyled } from "./styles";
import Head from "next/head";

interface LayoutProps {
  children: ReactChild | ReactChildren;
}

const Layout = ({ children }: LayoutProps) => (
  <LayoutStyled>
    <Head>
      <title>PokeNext</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <HeaderStyled>Header</HeaderStyled>
    {children}
    <FooterStyled>Footer</FooterStyled>
  </LayoutStyled>
);

export default Layout;
